name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        perl: [
          '5.10', '5.12', '5.14', '5.16', '5.18', '5.20', '5.22', '5.24',
          '5.26', '5.28', '5.30', '5.32', '5.34',
        ]

    runs-on: ubuntu-latest

    name: v${{ matrix.perl }}

    steps:
      - uses: actions/checkout@v2

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - run: perl -v

      - run: cpanm --cpanfile cpanfile --installdeps --notest .

      - run: prove -l
